server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8716/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
